### ISSUE TITLE
User Story#1 - Login and Logout

### ISSUE THREAD

**Issue by Borys-777** [Will-WHyd/Reindeer-Radar#1]
As a User, I would like to be able to login and logout on the website

**Comment by Borys-777** [comment]
As a User, I would like to be able to login and logout on the website. 

Acceptance Criteria:

- The user can log in to the website using the login form. 
- The user can log out on the website through the logout form.

**Comment by Will-WHyd** [comment]
Tasks:

- [ ] Install allauth onto project
- [ ] Confirm login and registration work
- [ ] Confirm correct formatting and redirection to login html templates
