### ISSUE TITLE
User Story#2 - Create lists

### ISSUE THREAD

**Issue by Borys-777** [Will-WHyd/Reindeer-Radar#2]
As a User, I would like to be able to create lists so that I can track the information about kids and presents on the website.

Acceptance Criteria:

The user can create a to-do list on the website. 
The user can view and edit the list.

**Comment by Will-WHyd** [comment]
Tasks

- [ ] Set up 'Household' model
- [ ] Set up the 'List' view and Template
- [ ] Confirm list displays
